//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.03 at 09:58:20 AM TRT 
//


package com.rd.soapservice.schemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rd.soapservice.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rd.soapservice.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Serilist }
     * 
     */
    public Serilist createSerilist() {
        return new Serilist();
    }

    /**
     * Create an instance of {@link SerilistResponse }
     * 
     */
    public SerilistResponse createSerilistResponse() {
        return new SerilistResponse();
    }

    /**
     * Create an instance of {@link Evraktipleri }
     * 
     */
    public Evraktipleri createEvraktipleri() {
        return new Evraktipleri();
    }

    /**
     * Create an instance of {@link EvraktipleriResponse }
     * 
     */
    public EvraktipleriResponse createEvraktipleriResponse() {
        return new EvraktipleriResponse();
    }

    /**
     * Create an instance of {@link Evraktipalanlari }
     * 
     */
    public Evraktipalanlari createEvraktipalanlari() {
        return new Evraktipalanlari();
    }

    /**
     * Create an instance of {@link EvraktipalanlariResponse }
     * 
     */
    public EvraktipalanlariResponse createEvraktipalanlariResponse() {
        return new EvraktipalanlariResponse();
    }

    /**
     * Create an instance of {@link Dosyaarabul }
     * 
     */
    public Dosyaarabul createDosyaarabul() {
        return new Dosyaarabul();
    }

    /**
     * Create an instance of {@link DosyaarabulResponse }
     * 
     */
    public DosyaarabulResponse createDosyaarabulResponse() {
        return new DosyaarabulResponse();
    }

    /**
     * Create an instance of {@link Evrakarabul }
     * 
     */
    public Evrakarabul createEvrakarabul() {
        return new Evrakarabul();
    }

    /**
     * Create an instance of {@link EvrakarabulResponse }
     * 
     */
    public EvrakarabulResponse createEvrakarabulResponse() {
        return new EvrakarabulResponse();
    }

    /**
     * Create an instance of {@link Evrakindir }
     * 
     */
    public Evrakindir createEvrakindir() {
        return new Evrakindir();
    }

    /**
     * Create an instance of {@link EvrakindirResponse }
     * 
     */
    public EvrakindirResponse createEvrakindirResponse() {
        return new EvrakindirResponse();
    }

    /**
     * Create an instance of {@link Indexyap }
     * 
     */
    public Indexyap createIndexyap() {
        return new Indexyap();
    }

    /**
     * Create an instance of {@link IndexyapResponse }
     * 
     */
    public IndexyapResponse createIndexyapResponse() {
        return new IndexyapResponse();
    }

}
